language: rust
rust:
  - nightly-2019-11-06

os:
  - linux
  - osx

cache: rust

install:
  - rustup target add thumbv7em-none-eabi
  - rustup target add riscv32imc-unknown-none-elf
  - rustup component add rustfmt-preview

script:
  - cargo fmt --all -- --check
  - cargo test --lib
  - ./build_examples.sh
