language: rust
rust:
  - nightly-2017-12-16


os:
- linux

cache:
  directories:
    - $HOME/gcc-arm-none-eabi-6_2-2016q4

script:
  - pushd $HOME
  - wget -c https://developer.arm.com/-/media/Files/downloads/gnu-rm/6-2016q4/gcc-arm-none-eabi-6_2-2016q4-20161216-linux.tar.bz2?product=GNU%20ARM%20Embedded%20Toolchain,64-bit,,Linux,6-2016-q4-major -O gcc.tar.bz2
  - tar -xjf gcc.tar.bz2
  - export PATH="$PATH:$HOME/gcc-arm-none-eabi-6_2-2016q4/bin"
  - popd
  - cargo build --verbose --all
  - cargo test --verbose --all
  - tools/install_dependencies.sh
  - rustup component add rust-src
  - ./build_examples.sh