language: rust
rust:
  - nightly-2018-03-06

os:
  - linux

cache:
  directories:
    - $HOME/.cargo
    - xargo/target
    - tock/userland/tools/elf2tbf/target

install:
  - rustup component add rust-src
  - rustup component add rustfmt-preview

script:
  - rustfmt --write-mode diff src/lib.rs
  - rustfmt --write-mode diff examples/*.rs
  - export RUSTFLAGS="$RUSTFLAGS -D warnings"
  - cargo test --lib
  - ./build_examples.sh
