language: rust
rust:
  - nightly-2018-04-12

os:
  - linux

cache:
  directories:
    - $HOME/.cargo
    - target
    - elf2tbf/target

install:
  - rustup target add thumbv7em-none-eabi
  - rustup component add rustfmt-preview

script:
  - rustfmt --check src/lib.rs
  - rustfmt --check examples/*.rs
  - cargo test --lib
  - ./build_examples.sh
