language: rust
rust:
  - nightly-2017-12-16

os:
- linux

cache:
  cargo: true
  directories:
    - $HOME/downloads


script: 
  - pushd $HOME
  - wget -c https://developer.arm.com/-/media/Files/downloads/gnu-rm/6-2016q4/gcc-arm-none-eabi-6_2-2016q4-20161216-linux.tar.bz2?product=GNU%20ARM%20Embedded%20Toolchain,64-bit,,Linux,6-2016-q4-major -O downloads/gcc.tar.bz2
  - pushd downloads
  - tar -xjf gcc.tar.bz2
  - popd
  - export PATH="$PATH:$HOME/downloads/gcc-arm-none-eabi-6_2-2016q4/bin"
  - popd
  - rm -rf target
  - tools/install_xargo.sh
  - rustup component add rust-src
  - export RUSTFLAGS="$RUSTFLAGS -D warnings"
  - cargo test --lib
  - ./build_examples.sh