language: rust
rust:
  - nightly-2018-11-30

os:
  - linux

cache: rust

install:
  - rustup target add thumbv7em-none-eabi
  - rustup component add rustfmt-preview

script:
  - rustfmt --check src/lib.rs
  - rustfmt --check examples/*.rs
  - cargo test --lib
  - ./build_examples.sh
