language: rust
rust:
  - nightly-2018-11-30

os:
  - linux

cache: rust

install:
  - rustup target add thumbv7em-none-eabi
  - rustup component add rustfmt-preview

script:
  - cargo fmt --all -- --check
  - cargo test --lib
  - ./build_examples.sh
