[package]
name = "tock"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
license = "MIT/Apache-2.0"

[dependencies]
linked_list_allocator = { git = "https://github.com/phil-opp/linked-list-allocator" }

[dev-dependencies]
corepack = { version="~0.3.1", default-features=false, features = ["alloc"] }
serde_derive = { version = "~1.0.10", default-features = false }
serde = { version = "~1.0.10", default-features = false }

[profile.dev]
panic = "abort"
lto = true

[profile.release]
panic = "abort"
lto = true
debug = true
