[package]
name = "tock"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
license = "MIT/Apache-2.0"

[dependencies]
linked_list_allocator = "0.6.3"

[build-dependencies]
proc-macro2 = "=0.4.13"

[dev-dependencies]
corepack = { version = "0.4.0", default-features = false, features = ["alloc"] }
serde_derive = { version = "=1.0.77", default-features = false }
serde = { version = "=1.0.77", default-features = false }

[profile.dev]
panic = "abort"
lto = true

[profile.release]
panic = "abort"
lto = true
