[package]
name = "tock"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
license = "MIT/Apache-2.0"

[dependencies]

[profile.dev]
panic = "abort"
lto = true

[profile.release]
panic = "abort"
lto = true
