[target.thumbv7em-none-eabi]
toolchain = "nightly-2017-09-20"
image = "tockimage:latest"

[target.thumbv7em-tock-eabi]
toolchain = "nightly-2017-09-20"
image = "tockimage:latest"

[build.env]
passthrough = [
  "TOCK_KERNEL_VERSION"
]
