[package]
name = "async-support"
version = "0.1.0"
authors = ["Woyten <woyten.tielesch@online.de>"]
edition = "2018"
description = "Libtock specific patch of core library for async-await syntax in a no_std environment"

[dependencies]
