# This workflow verifies libtock-rs is usable on Mac OS.

name: ci-mac-os

# We run this workflow during pull request review, but not for Bors merges, as
# it takes over an hour to run.
on: pull_request

jobs:
  ci-mac-os:
    runs-on: macos-10.15

    steps:
      # Clones a single commit from the libtock-rs repository. The commit cloned
      # is a merge commit between the PR's target branch and the PR's source.
      - name: Clone repository
        uses: actions/checkout@v2.3.0

      # Install the toolchains we need, then run `cargo build`.
      - name: Build and Test
        run: |
          brew tap riscv/riscv
          brew update
          brew install riscv-gnu-toolchain --with-multilib
          cd "${GITHUB_WORKSPACE}"
          LIBTOCK_PLATFORM=hifive1 cargo build -p libtock_runtime \
            --target=riscv32imac-unknown-none-elf
